services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


networks:
  inception:
    driver: bridge